#!/bin/sh
# Produce individual UFOs from Glyphs files
psfglyphs2ufo source/masters/LisuBosaUpright.glyphs source/masters
psfglyphs2ufo source/masters/LisuBosaItalic.glyphs source/masters
psfremovegliflibkeys source/masters/LisuBosa-Regular.ufo public.verticalOrigin
psfremovegliflibkeys source/masters/LisuBosa-ExtraLight.ufo public.verticalOrigin
psfremovegliflibkeys source/masters/LisuBosa-Black.ufo public.verticalOrigin
psfremovegliflibkeys source/masters/LisuBosa-Italic.ufo public.verticalOrigin
psfremovegliflibkeys source/masters/LisuBosa-ExtraLightItalic.ufo public.verticalOrigin
psfremovegliflibkeys source/masters/LisuBosa-BlackItalic.ufo public.verticalOrigin
./preflight
