#!/bin/sh

# Fix up glifs in files touched by FontForge and normalize
psffixffglifs -p checkfix=fix source/masters/BosaLisuMaster-Regular.ufo
psffixffglifs -p checkfix=fix source/masters/BosaLisuMaster-ExtraLight.ufo
psffixffglifs -p checkfix=fix source/masters/BosaLisuMaster-Black.ufo
psffixffglifs -p checkfix=fix source/masters/BosaLisuMaster-Italic.ufo
psffixffglifs -p checkfix=fix source/masters/BosaLisuMaster-ExtraLightItalic.ufo
psffixffglifs -p checkfix=fix source/masters/BosaLisuMaster-BlackItalic.ufo

# Following sync will copy psnames and glyphorder updates to all fonts
psfsyncmasters --complex source/BosaUpright.designspace source/BosaItalic.designspace
