#!/bin/sh

# This normalization will also run check and fix routines
psfnormalize -p checkfix=fix source/Bosa-Regular.ufo

# Following sync will copy psnames and glyphorder updates to all fonts
# psfsyncmasters source/LisuNewRoman.designspace source/LisuNewItalic.designspace
