#!/bin/sh

# This normalization will also run check and fix routines
psfnormalize -p checkfix=fix source/masters/LisuBosaMaster-Regular.ufo
psfnormalize -p checkfix=fix source/masters/LisuBosaMaster-ExtraLight.ufo
psfnormalize -p checkfix=fix source/masters/LisuBosaMaster-Black.ufo
psfnormalize -p checkfix=fix source/masters/LisuBosaMaster-Italic.ufo
psfnormalize -p checkfix=fix source/masters/LisuBosaMaster-ExtraLightItalic.ufo
psfnormalize -p checkfix=fix source/masters/LisuBosaMaster-BlackItalic.ufo

# Following sync will copy psnames and glyphorder updates to all fonts
psfsyncmasters --complex source/LisuBosaUpright.designspace source/LisuBosaItalic.designspace
